---
name: 'CD'
on:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ghcr.io/${{ github.repository }}:$GITHUB_SHA .

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image to registry
        run: |
          docker tag ghcr.io/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository }}:develop
          docker push ghcr.io/${{ github.repository }}:$GITHUB_SHA
          docker push ghcr.io/${{ github.repository }}:develop

  # create-sentry-release:
  #   runs-on: ubuntu-24.04
  #   name: |
  #     Sentry Rel.: ${{ matrix.project }} (${{ matrix.environment }})
  #   if: github.ref_name == 'main' || startsWith(github.ref_name, 'release/') || contains(github.event.pull_request.labels.*.name, 'preview')
  #   needs:
  #     - publish-docker-images
  #     - get-commit-sha
  #   strategy:
  #     matrix:
  #       environment: ['preview', 'staging']
  #       project: ['core', 'web']
  #       exclude:
  #         - environment: ${{ (github.ref_name == 'main' || startsWith(github.ref_name, 'release/')) && 'preview' || 'staging' }}
  #   steps:
  #     # Sentry does need a repository it seems
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: getsentry/action-release@v1
  #       env:
  #         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  #         SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  #         SENTRY_PROJECT: ${{ matrix.project }}
  #       with:
  #         environment: ${{ matrix.environment }}
  #         version: ${{ needs.get-commit-sha.outputs.commit_sha }}
