---
name: Tag production image

on:
  push:
    tags:
      - "*"

jobs:
  tagProdVersion:
    runs-on: ubuntu-latest
    name: 'Push semver-tagged image to registry and notify sentry of release'
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull current image
        run: |
          docker pull ghcr.io/${{ github.repository }}:$GITHUB_SHA

      - name: push tagged image
        run: |
          docker tag ghcr.io/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository }}:$GITHUB_REF_NAME
          docker tag ghcr.io/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:$GITHUB_REF_NAME
          docker push ghcr.io/${{ github.repository }}:latest
